### ISSUE TITLE
Panic when processing todomvc.wasm

### ISSUE THREAD

**Issue by atoav** [Extrawurst/rust-webview-todomvc-yew#5]
I cloned this project, installed cargo-web and tried to run it with `make run`. This leads to the following panic while processing `todomvc.wasm`:

```
    Processing "todomvc.wasm"...                                                                                                                                  
thread 'main' panicked at 'unknown name section chunk type: 7', /home/myusername/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-web-0.6.26/src/wasm_context.rs:642:
41                                                                                                                                                                
stack backtrace:                                                                                                                                                  
   0: rust_begin_unwind                                                                                                                                           
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt                                                                                                                             
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   2: cargo_web::wasm_context::Context::from_module
   3: cargo_web::wasm::process_wasm_file 
   4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   5: cargo_web::cargo_shim::BuildConfig::build_internal
   6: cargo_web::cargo_shim::BuildConfig::build
   7: cargo_web::build::Project::build_or_check
   8: cargo_web::cmd_build::command_build_or_check
   9: cargo_web::run
  10: cargo_web::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
make: *** [Makefile:13: build-wasm] Error 101
```

## Details

- Operating System: `Ubuntu 20.04.3 LTS (focal)`
- Cargo Version: `cargo 1.56.0 (4ed5d137b 2021-10-04)`
- Cargo-Web Version: `cargo-web 0.6.26`

**Comment by atoav** [comment]
## Full backtrace

```
Processing "todomvc.wasm"...
thread 'main' panicked at 'unknown name section chunk type: 7', /home/myusername/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-web-0.6.26/src/wasm_context.rs:642:41
stack backtrace:
   0:     0x563d9eec98dc - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x563d9eec98dc - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563d9eec98dc - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563d9eec98dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x563d9eef12bc - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x563d9eec14d5 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x563d9eecba50 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563d9eecba50 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563d9eecba50 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x563d9eecb607 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x563d9eecc104 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x563d9eecbbe0 - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:     0x563d9eec9da4 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563d9eecbb49 - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:     0x563d9e87c4fb - std::panicking::begin_panic_fmt::hc15cd62c02c70986
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
  15:     0x563d9e8ea52c - cargo_web::wasm_context::Context::from_module::hece47162608554d2
  16:     0x563d9e9d97f4 - cargo_web::wasm::process_wasm_file::hbe93b4a0639ce6a9
  17:     0x563d9e9fb177 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h235d72fbfce83fd8
  18:     0x563d9e989ec0 - cargo_web::cargo_shim::BuildConfig::build_internal::h3f2b4a3774724ea4
  19:     0x563d9e9874b1 - cargo_web::cargo_shim::BuildConfig::build::hbb856998108c5985
  20:     0x563d9ea114b4 - cargo_web::build::Project::build_or_check::hc4d552356988e8ea
  21:     0x563d9e98b05b - cargo_web::cmd_build::command_build_or_check::hbafeccd6f9d497e9
  22:     0x563d9e938443 - cargo_web::run::h03af57ace2a93506
  23:     0x563d9e886c5b - cargo_web::main::h765b0e2ca6c5b035
  24:     0x563d9e885623 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha16d626f2759aa80
  25:     0x563d9e88c579 - std::rt::lang_start::{{closure}}::h369108a85a638b55
  26:     0x563d9eecc70a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  27:     0x563d9eecc70a - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  28:     0x563d9eecc70a - std::panicking::try::h675520ee37b0fdf7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  29:     0x563d9eecc70a - std::panic::catch_unwind::h803430ea0284ce79
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  30:     0x563d9eecc70a - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  31:     0x563d9eecc70a - std::panicking::try::do_call::hf60f106700df94b2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  32:     0x563d9eecc70a - std::panicking::try::hb2022d2bc87a9867
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  33:     0x563d9eecc70a - std::panic::catch_unwind::hbf801c9d61f0c2fb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  34:     0x563d9eecc70a - std::rt::lang_start_internal::hdd488b91dc742b96
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  35:     0x563d9e886df2 - main
  36:     0x7f016acec0b3 - __libc_start_main
  37:     0x563d9e87d9fe - _start
  38:                0x0 - <unknown>
make: *** [Makefile:13: build-wasm] Error 101
```

**Comment by atoav** [comment]
Solved this myself – I had to clone this project using the `--recurse-submodules` flag. Why this isn't the default behaviour of git is beyond me.

```
git clone --recurse-submodules https://github.com/extrawurst/rust-webview-todomvc-yew.git
```
